### ISSUE TITLE
With Flatpak's nvidia-525-105-17 no GPU acceleration

### ISSUE THREAD

**Issue by Flashwalker** [flathub/com.github.Eloston.UngoogledChromium#111]
|  |  |
| --- | --- |
| Host driver: | `nvidia-525-105-17` |
| Flatpak driver: | `nvidia-525-105-17` |
| Result: | No GPU acceleration ❌ |

![image](https://github.com/flathub/com.github.Eloston.UngoogledChromium/assets/2188215/786a33af-371d-4dd7-b254-8c1c4a810de4)

|  |  |
| --- | --- |
| Host driver: | `nvidia-525-105-17` |
| Flatpak driver: | `nvidia-525-85-05` or `nvidia-525-89-02` |
| Result: | GPU acceleration is OK ✅ |

![image](https://github.com/flathub/com.github.Eloston.UngoogledChromium/assets/2188215/0bced0da-244f-4163-9a5d-ad9a822062cb)

Command:
```bash
export __NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia PW_PRIME_RENDER_OFFLOAD=1
flatpak run --env=__NV_PRIME_RENDER_OFFLOAD=1 --env=__GLX_VENDOR_LIBRARY_NAME=nvidia --env=PW_PRIME_RENDER_OFFLOAD=1 \
    --branch=stable \
    --arch=x86_64 \
    --command=/app/bin/chromium \
    --file-forwarding \
    com.github.Eloston.UngoogledChromium \
    @@u \
        --enable-gpu-rasterization \
        --enable-accelerated-2d-canvas \
        --enable-accelerated-video-decode \
        --ignore-gpu-blocklist \
        --enable-unsafe-webgpu \
        --enable-zero-copy \
        --enable-features=CanvasOopRasterization,EnableDrDc,RawDraw,UseSkiaRenderer,Vulkan \
        --user-data-dir=/tmp/unchrfltmp \
        --custom-ntp=chrome://gpu \
        "$@" \
    @@
```

Graphics:
```bash
export __NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia PW_PRIME_RENDER_OFFLOAD=1 
inxi -G
```

```
Graphics:
  Device-1: Intel HD Graphics 630 driver: i915 v: kernel
  Device-2: NVIDIA GP107M [GeForce GTX 1050 Mobile] driver: nvidia
    v: 525.105.17
  Device-3: Sunplus Innovation Integrated_Webcam_HD type: USB
    driver: uvcvideo
  Display: x11 server: X.Org v: 1.21.1.3 driver: X:
    loaded: modesetting,nvidia unloaded: fbdev,nouveau,vesa gpu: i915
    resolution: 1920x1080~60Hz
  OpenGL: renderer: NVIDIA GeForce GTX 1050/PCIe/SSE2
    v: 4.6.0 NVIDIA 525.105.17
```
